repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/pycqa/flake8
    rev: '3.9.2'  # pick a git hash / tag to point to: https://github.com/pycqa/flake8/tags
    hooks:
    - id: flake8
  - repo: local
    hooks:
    - id: pyright
      name: pyright
      entry: pyright
      language: node
      pass_filenames: false
      types: [python]
      additional_dependencies: ['pyright@1.1.99']